In [1]:
#Only run this once to load in the dataset from kaggle
import kagglehub

# Download latest version
path = kagglehub.dataset_download("pacificrm/skindiseasedataset")

print("Path to dataset files:", path)

100%|█████████████████████████████████████████████████████████████████████████████| 1.36G/1.36G [01:33<00:00, 15.6MB/s]

Extracting files...


Path to dataset files: C:\Users\luqma\.cache\kagglehub\datasets\pacificrm\skindiseasedataset\versions\6


In [10]:
# Declares the classifications
diseases = [('an', 'Acne'), ('ac', 'Actinic_Keratosis'), ('be', 'Benign_tumors'),
           ('bu', 'Bullous'),('ca', 'Candidiasis'), ('de', 'DrugEruption'),
          ('ec','Eczema'), ('ib','Infestations_Bites'),('li','Lichen'),
          ('lu','Lupus'), ('mo','Moles'),('ps','Psoriasis'),
           ('ro','Rosacea'), ('sk','Seborrh_Keratoses'),('sc','SkinCancer'),
           ('sd','Sun_Sunlight_Damage'), ('ti','Tinea'),('un','Unknown_Normal'),
           ('vt','Vascular_Tumors'), ('va','Vasculitis'),('vi','Vitiligo'),
           ('wa','Warts')]

In [13]:
# Reads the images
import os
import cv2

# Set your folder path to where the dataset is, After downloading it I placed it in the same folder.
folder_path = r'SkinDisease/train/' # Loads the training set

# Create an empty list to store images
images = []


# Loop through all files in the folder
for disease in diseases:  
    imageList = []
    newFolderPath = folder_path + disease[1]
    image_files = [f for f in os.listdir(newFolderPath)]
    for filename in image_files[:1]: # Choose how many images to load from each folder here. Remove [] to load all of them.
        file_path = os.path.join(newFolderPath, filename)
        img = cv2.imread(file_path)
        if img is not None:
            imageList.append(img)
        else:
            print(f"Warning: Failed to read {filename}")
    images.append(imageList)

print(f"Total images loaded: {len(images)}")

Total images loaded: 22


In [35]:
h, w, c = images[0][0].shape # the image returns height, width and color information
print(h, w, c)

472 720 3


In [37]:
import numpy as np

In [40]:
image_db = []
for img in images:
        image_db.append(im.reshape(-1)) # Reduces the image into one dimention the same as h * w * c
    
image_db = np.squeeze(np.array(image_db))

In [41]:
print(image_db)
print(image_db.shape)

[[106 134 181 ...  52  93 115]
 [106 134 181 ...  52  93 115]
 [106 134 181 ...  52  93 115]
 ...
 [106 134 181 ...  52  93 115]
 [106 134 181 ...  52  93 115]
 [106 134 181 ...  52  93 115]]
(22, 1147500)


In [43]:
labels = []
for c in diseases:
    labels.extend([c[0] for i in range(1)]) # 1 because we only loaded 1 image per classificatino, change this when needed.

In [44]:
# sanity check
print(labels[0]) # should be an
print(labels[1]) # should be ac
print(labels[2]) # should be be
print(labels[3]) # should be bu

an
ac
be
bu
